"""initial migration

Revision ID: 41a8a3bf9438
Revises: None
Create Date: 2015-03-11 17:26:25.468000

"""

# revision identifiers, used by Alembic.
revision = '41a8a3bf9438'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
