"""add confirmed

Revision ID: 176c5327e81e
Revises: 56ded6d7f90d
Create Date: 2015-03-13 13:22:24.343000

"""

# revision identifiers, used by Alembic.
revision = '176c5327e81e'
down_revision = '56ded6d7f90d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
