"""init roles

Revision ID: 1c5698276dbf
Revises: 41a8a3bf9438
Create Date: 2015-03-12 13:31:17.890000

"""

# revision identifiers, used by Alembic.
revision = '1c5698276dbf'
down_revision = '41a8a3bf9438'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
