"""modify db

Revision ID: 3ca2b2fb577d
Revises: 4fc27749aca3
Create Date: 2015-03-13 17:41:53.546000

"""

# revision identifiers, used by Alembic.
revision = '3ca2b2fb577d'
down_revision = '4fc27749aca3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
