"""add some column

Revision ID: 48227830f8b1
Revises: 2565471aa91d
Create Date: 2015-03-16 15:34:05.843000

"""

# revision identifiers, used by Alembic.
revision = '48227830f8b1'
down_revision = '2565471aa91d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
