"""add body_html

Revision ID: afdbb5ef4d
Revises: 31bd46c47a87
Create Date: 2015-03-17 15:17:24.125000

"""

# revision identifiers, used by Alembic.
revision = 'afdbb5ef4d'
down_revision = '31bd46c47a87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
